const logInOutActionTypes = {
  LOGIN_REQUEST: 'LOGIN/REQUEST',
  LOGIN_SUCCESS: 'LOGIN/SUCCESS',
  LOGIN_FAILURE: 'LOGIN/FAILURE',
  LOGOUT: 'LOGOUT',
  GETALL_REQUEST: 'GETALL/REQUEST',
  GETALL_SUCCESS: 'GETALL/SUCCESS',
  GETALL_FAILURE: 'GETALL/FAILURE',
};

export default logInOutActionTypes;
